export const studentData = {
    id: "s1",
    name: "John Doe",
    email: "john.doe@example.com",
    profilePicture: "/placeholder.svg?height=200&width=200",
  }
  
  export const tutorsData = [
    {
      id: "t1",
      name: "Dr. Sarah Johnson",
      subject: "Mathematics",
      experience: 8,
      education: "Ph.D. in Mathematics",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.9,
      reviewCount: 124,
    },
    {
      id: "t2",
      name: "Prof. Michael Chen",
      subject: "Physics",
      experience: 12,
      education: "Ph.D. in Theoretical Physics",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.8,
      reviewCount: 98,
    },
    {
      id: "t3",
      name: "Emma Rodriguez",
      subject: "English Literature",
      experience: 6,
      education: "M.A. in English",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.7,
      reviewCount: 87,
    },
    {
      id: "t4",
      name: "Dr. James Wilson",
      subject: "Chemistry",
      experience: 10,
      education: "Ph.D. in Chemistry",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.9,
      reviewCount: 112,
    },
    {
      id: "t5",
      name: "Olivia Thompson",
      subject: "History",
      experience: 7,
      education: "M.A. in History",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.6,
      reviewCount: 76,
    },
    {
      id: "t6",
      name: "Dr. Robert Lee",
      subject: "Computer Science",
      experience: 9,
      education: "Ph.D. in Computer Science",
      profilePicture: "/placeholder.svg?height=300&width=300",
      rating: 4.8,
      reviewCount: 103,
    },
  ]
  
  export const requestsData = [
    {
      id: "r1",
      tutorId: "t1",
      tutorName: "Dr. Sarah Johnson",
      subject: "Mathematics",
      status: "accepted",
      date: "2023-05-15",
    },
    {
      id: "r2",
      tutorId: "t2",
      tutorName: "Prof. Michael Chen",
      subject: "Physics",
      status: "pending",
      date: "2023-05-18",
    },
    {
      id: "r3",
      tutorId: "t4",
      tutorName: "Dr. James Wilson",
      subject: "Chemistry",
      status: "rejected",
      date: "2023-05-10",
    },
    {
      id: "r4",
      tutorId: "t6",
      tutorName: "Dr. Robert Lee",
      subject: "Computer Science",
      status: "pending",
      date: "2023-05-20",
    },
  ]
  
  export const messagesData = [
    {
      id: "m1",
      tutorId: "t1",
      tutorName: "Dr. Sarah Johnson",
      tutorAvatar: "/placeholder.svg?height=100&width=100",
      lastMessage: "I've reviewed your latest assignment. Let's discuss it in our next session.",
      time: "10:30 AM",
      unread: true,
    },
    {
      id: "m2",
      tutorId: "t3",
      tutorName: "Emma Rodriguez",
      tutorAvatar: "/placeholder.svg?height=100&width=100",
      lastMessage: "Don't forget to read Chapter 5 before our class tomorrow!",
      time: "Yesterday",
      unread: false,
    },
    {
      id: "m3",
      tutorId: "t6",
      tutorName: "Dr. Robert Lee",
      tutorAvatar: "/placeholder.svg?height=100&width=100",
      lastMessage: "Here's the link to the coding resources we discussed.",
      time: "2 days ago",
      unread: false,
    },
    {
      id: "m4",
      tutorId: "t5",
      tutorName: "Olivia Thompson",
      tutorAvatar: "/placeholder.svg?height=100&width=100",
      lastMessage: "Your essay on World War II was excellent. I've given you detailed feedback.",
      time: "3 days ago",
      unread: false,
    },
  ]
  